---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  tidy:
    desc: Runs go mod tidy
    cmds:
      - go mod tidy

  test:
    desc: Runs go test
    cmds:
      - go test -v ./...

  docs:
    desc: Run http server on port :6060 with documentation
    cmds:
      - godoc -http=:6060
